os: linux
dist: bionic

services: docker

language: shell

branches:
  only:
    - master

before_script:
  - env | sort
  - dir="."
  - export TAG=travis
  - export VCS_REF=`git rev-parse --short HEAD`
  - export BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
  - export IMAGE_NAME=docker-coturn

script:
  # Test containers build
  - docker-compose -f docker-compose.test.yml build
  - docker images
  # Test containers run
  - travis_retry docker-compose -f docker-compose.test.yml up -d
  - docker-compose -f docker-compose.test.yml logs -f "sut"
  - docker-compose -f docker-compose.test.yml ps
  - docker-compose -f docker-compose.test.yml logs "coturn"
  - docker-compose -f docker-compose.test.yml ps "coturn" | grep "Up"
  - docker-compose -f docker-compose.test.yml ps "sut" | grep "Exit 0"
  # Test containers can be dropped and restarted
  - docker-compose -f docker-compose.test.yml down
  - travis_retry docker-compose -f docker-compose.test.yml up -d
  - docker-compose -f docker-compose.test.yml logs -f "sut"
  - docker-compose -f docker-compose.test.yml ps
  - docker-compose -f docker-compose.test.yml logs "coturn"
  - docker-compose -f docker-compose.test.yml ps "coturn" | grep "Up"
  - docker-compose -f docker-compose.test.yml ps "sut" | grep "Exit 0"

notifications:
  email: false

jobs:
  allow_failures:
    - env: VERSION=master

env: # Environments
  - VERSION=4.5.1.3
  - VERSION=master
