os: linux
dist: bionic

services: docker

language: shell

branches:
  only:
    - master

before_script:
  - env | sort
  - name="coturn"
  - image="monogramm/docker-coturn:travis"
  - dir="."

script:
  - travis_retry docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=`git rev-parse --short HEAD` --build-arg VERSION=$VERSION -t "$image" "$dir"
  - docker images
  - docker run --name "$name" -d "$image" "$dir" && sleep 60
  - docker ps
  - docker logs "$name"
  - docker ps | grep "Up" || exit 1

notifications:
  email: false

jobs:
  allow_failures:
    - env: VERSION=master

env: # Environments
  - VERSION=4.5.1.3
  - VERSION=master
